### ISSUE TITLE
Guidance on Rotation

### ISSUE THREAD

**Issue by nitmatgeo** [Azure/KeyVault-Secrets-Rotation-Template-PowerShell#1]
Hi Jack (@jlichwa ),
I am new to exploring Key Vault (_kva_) stuffs, currently I deployed few key vaults and I managed to encrypt some VMs using Customer Managed keys. Our new requirement is to use HSM keys instead of RSA. We deploy all resources using Terraform and deployed via Az DevOps, but my challenge is -rotating RSA/HSM keys while the key generation happens in Terraform. 
1. Can I achieve the same using terraform to create Resources required to rotate kva keys?
2. For rotation in addition to source kva, only Az function & event grid is required?
3. What exactly needs to be coded in function app? 
4. I couldn't find any Az CLI syntax to generate new version of keys, any URL of MS documentation?
5. How is the triggering of event upon key/secret expiry set up in a kva?
6. The apply of latest version is automatic, right? Especially to the encrypted disks?

Your time and response would be a great help 😄 If am not mistake, I think in coming days, this topic would be a hot requirement!

**Comment by jlichwa** [comment]
Hello,

This rotation template and examples are for secrets (credentials for services/dbs) not for encryption keys.
1. I'm not familiar with Terraform, but in theory you should be able to generate keys through it if you are able to make a call with PS, CLI then it can be possible, ARM templates will not allow you to rotate existing key.
2. Yes you can use Function with Event Grid to trigger function based on key expiration or you can just create scheduled function to generate new key.
3. In case of encryption keys, it will be just generating new key version with exactly same type, size etc... as existing key)
4. Key create will create new version if key with this name exist already https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az_keyvault_key_create
5. You can learn more on subscribing to events here https://docs.microsoft.com/en-us/azure/key-vault/general/event-grid-overview
6. Storage, Disk etc... yes they are automatically refresh to new version.

We are actively working on encryption key rotation through rotation policy (similar to certificates - https://docs.microsoft.com/en-us/azure/key-vault/certificates/tutorial-rotate-certificates).

**Comment by nitmatgeo** [comment]
Thank you Jack @jlichwa for your very prompt response, I will look into the references shared and will update you if I get stuck or have an output. I am closing the issue for now :)

-NitinMathewGeorge

**Comment by nitmatgeo** [comment]
@jlichwa  Have doubt, am stuck up here. This URL -https://docs.microsoft.com/en-us/azure/event-grid/event-schema-key-vault?tabs=event-grid-event-schema mentions _Event Grid schema for Microsoft.KeyVault.SecretNewVersionCreated_.

While exploring Az Functions using PowerShell-
1. under FunctionApp --> Functions --> Event Grid trigger [_I had to use this instead of http trigger_]
2. I saw by default some lines were there, as below-
```
param($eventGridEvent, $TriggerMetadata)

# Make sure to pass hashtables to Out-String so they're logged correctly
$eventGridEvent | Out-String | Write-Host
```
3. When I test/run I see `input` section that demands a key & body. I took default key and how do I know the test data? Isn't there a way to print the response dynamically based on responses?

I thought the code in Point 2 would print the data generated from KVA event, but I see from app insight that 2 events were triggered but those 2 appearing as failed and 0 in success. Any material to understand this flow?

**Comment by jlichwa** [comment]
You can't test/run event trigger. I'm confused what is your use case, what are you trying to accomplish. This is a template/skeleton for building your own custom rotation of credentials for service or database...  with example of steps here https://github.com/Azure/KeyVault-Secrets-Rotation-Template-PowerShell/blob/main/Project-Template-Instructions.md

**Comment by nitmatgeo** [comment]
Thank you Jack, apologies if I end up confusing again, I will go through the shared URL a bit more detailed tomorrow. Meanwhile,

Prime Objective:
1. Monitor Key Vaults in all subscription for any Key Expiry 🆗 -using event grid subscription per each key vault
2. If near expiry, then trigger an event with end point as functionApp 🆗  -able to configure this while setting up Event Grid Subscription
3. Before I write PS functions, I wanted to output the response triggered by the event; so that, I will know how do I filter out a specific topic, extract key vault name, key name, and so on based on the response type. At this step, can't _(or how do I)_ I just simply print a text [Write-Host "welcome"] in PS & view the output? **or** visualize the response from event grid trigger & see the output response?

**Comment by jlichwa** [comment]
So this is Secrets rotation template only (not key rotation). 
It is under open source with MIT license:
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

Feel free to create your own fork and modify it for any scenario at your own.

At this moment there is no solution for Key rotation as far as I know and you will have build your own. 

I'm not an expert on functions and this just an example...If you have problems with functions you will need to reach out to their team. 
I found a doc for Functions bindings which can help https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid

**Comment by nitmatgeo** [comment]
Hi Jack (@jlichwa ),
_Just an update-_ 
I have raised another query requesting more clarity as mentioned about. The secret rotation uses a HTTP trigger whereas, from MS documentations, I understood that Event Grid trigger is expected and I am not certain how do I script. Basically to know the event API response for an event (_To use Event Grid Viewer etc. looks little complex, as I am not from a programming background_).

Meanwhile MS team responds, let me explore if Logic App works out! 

#Update01:
Logic App seems to have better clarity, I could get the KVA event into Logic App and then convert it to as HTTP request. Now I think your script for Secret can be referred for Key generation. Will start working on this part now 😄

**Comment by nitmatgeo** [comment]
@jlichwa Another quick help, please...
To use Az PowerShell cmdlet inside AzFunction, 
1. Do we need to install any modules? (_The term 'Get-AzKeyVaultKey' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again_)
2. Do I need to generate a token or login session in AzFunction before executing scripts like below?
`
Get-AzKeyVaultKey -VaultName $keyVAultName -Name $keyName
`

Also, am yet to hear from MS on other request; but I managed to use logic app and get the event response. Basically I was trying to figure out, how do I get a sample [like here](https://github.com/Azure/KeyVault-Secrets-Rotation-Template-PowerShell/blob/main/AKVServiceTypeRotation/sample.dat).

PS: Once the objective is met, will document and update you 👍

**Comment by nitmatgeo** [comment]
Just an update, things worked; once I get some time, I will have a fork and stuck with logic app deployment with terraform. I hope to sort that as well. @jlichwa Thank you 😀
